#!/usr/bin/env bash
# Update package list
# change listening port to 80 and output hello world in htm
sudo apt update
sudo apt install nginx -y
sudo sed -i 's/listen \[::\]:80 default_server;/listen 80;/' /etc/nginx/sites-available/default
sudo service nginx restart
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
curl http://localhost:80 | grep "Hello World!" >/dev/null

if [ $? -eq 0 ]
then
  echo "Nginx installed and configured successfully!"
else
  echo "Nginx installation or configuration failed!"
fi
