#!/usr/bin/env bash
# Update the package index
apt-get update
apt-get install -y nginx
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
echo "
server {
    listen 80;
    location / {
        return 200 'Hello World!';
    }
}" > /etc/nginx/sites-available/default
kill $(cat /run/nginx.pid)

