#!/usr/bin/env bash 
#this is a code for bad  luck
count=0
while [ $count -lt 10 ]
do
  if [ $count -eq 4 ]
	then
	  echo "bad luck"
  elif [ $count -eq 8 ]
	then
	  echo "good luck"
  else
	echo "best school"
  fi
  count=$((count+1))
done
