#!/usr/bin/env bash
# Loop through each file and directory in the current directory
for file in *
do
  # Check if the file is a hidden file
  if [[ "${file}" != .* ]]
  then
    # Display the file or directory name
    echo "${file}"
  fi
done
