#!/usr/bin/env bash
#	this script generates 2 ssh keys with 4096 bytes 
#	the type is rsa and the private key is stored in the file school
#	with passcode betty
ssh keyg-gen -t rsa -b 4096 -f school -N betty
